[project]
name = "sso-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "pyjwt>=2.9.0",
    "scalekit-sdk-python>=1.0.6",
    "uvicorn>=0.34.0",
]
